# Generated by Django 5.2.1 on 2025-05-21 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage_tag_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
