# Generated by Django 5.2.1 on 2025-05-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
