# Generated by Django 5.2.1 on 2025-05-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_report'),
        ('projects', '0008_delete_review'),
    ]

    operations = [
    ]
